import { defineConfig } from "vitepress";

const repo = "https://github.com/elias-ems/elias-ems";

export default defineConfig({
  title: "Elias ems",
  description:
    "An open-source home energy management system that runs inside Home Assistant.",

  // The repository is elias-ems/elias-ems, so GitHub Pages serves it from
  // https://elias-ems.github.io/elias-ems/. This becomes "/" if a custom domain
  // is ever pointed at it.
  base: "/elias-ems/",

  // `site/internals/` is generated by scripts/sync-docs.mjs and every link in it
  // was rewritten by rules that page cannot see. Dead-link checking stays on so
  // a rule that stops matching fails the build instead of shipping a 404.
  cleanUrls: true,

  head: [
    ["meta", { name: "theme-color", content: "#0288d1" }],
    [
      "link",
      { rel: "icon", href: "/elias-ems/favicon.svg", type: "image/svg+xml" },
    ],
  ],

  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/", activeMatch: "/guide/" },
      {
        text: "Under the hood",
        link: "/internals/architecture",
        activeMatch: "/internals/",
      },
      { text: "Contributing", link: "/contributing" },
    ],

    sidebar: {
      "/guide/": [
        {
          text: "Getting started",
          items: [
            { text: "What it is", link: "/guide/" },
            { text: "Installing", link: "/guide/install" },
            { text: "Configuring", link: "/guide/configure" },
          ],
        },
        {
          text: "Using it",
          items: [
            { text: "The dashboard", link: "/guide/dashboard" },
            { text: "Battery control", link: "/guide/battery-control" },
            { text: "Dynamic prices", link: "/guide/prices" },
            { text: "Diagnostics", link: "/guide/diagnostics" },
            { text: "Troubleshooting", link: "/guide/troubleshooting" },
          ],
        },
      ],
      "/internals/": [
        {
          text: "Under the hood",
          items: [
            { text: "Architecture", link: "/internals/architecture" },
            { text: "Battery control", link: "/internals/battery-control" },
            { text: "Live readings", link: "/internals/live-readings" },
            { text: "Diagnostics", link: "/internals/diagnostics" },
            { text: "Dynamic prices", link: "/internals/dynamic-prices" },
          ],
        },
      ],
    },

    outline: [2, 3],
    search: { provider: "local" },
    socialLinks: [{ icon: "github", link: repo }],

    editLink: {
      pattern: `${repo}/edit/main/site/:path`,
      text: "Edit this page on GitHub",
    },

    footer: {
      message: `<a href="${repo}/issues">Report an issue</a>`,
      copyright: "© 2026 Elias Lecomte",
    },
  },
});
