name: "Elias ems"
version: "1.0.0-alpha.13"
slug: "elias-ems"
description: "Home Energy Management System (HEMS) that complements and extends Home Assistant"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 3000
homeassistant_api: true
panel_icon: mdi:home-analytics
startup: application
boot: auto
